### ISSUE TITLE
GSI tree huh?

### ISSUE THREAD

**Issue by SparXFusion** [Fraschze97/device_realme_RMX1941#2]
welp, since i left c2 nothing has changed, even one bit of improvement y'all have....also why you need to add gsi specific stuffs to tree which is already partially gsi-like tree xD, Go build GSI instead of doing this nonsense lmao. Ah wait, better option is to just go use gsi with some nonsense modules to boost perf and smoothness.

**Comment by Fraschze97** [comment]
its up to me lol , why are you busy taking care of other people ? i never bother you.

**Comment by Dreadwyrm** [comment]
@Fraschze97 Anjay menggelud di github

**Comment by Fraschze97** [comment]
@SparXFusion sakhtivel membuat masalah

**Comment by SparXFusion** [comment]
> @SparXFusion sakhtivel membuat masalah

only real ppl know who is trouble maker in the name of "help" :D 
also go learn stuffs and stop doing nonsense in the name of "learning" ur tree has jackshit quality duh
